### ISSUE TITLE
Installation problem (macOS)

### ISSUE THREAD

**Issue by PatrickJohnston** [lbusett/sprawl#74]
Thanks for writing this useful package. After discovering it, I installed and was using it without a hitch. I recently had to reinstall it, and am now unable to get the package to install. 

I'm running macOS 10.13.6 Beta, R 3.5.0, and have hdf4, gdal, and gdal2 installed via Homebrew. My Python distribution is Anaconda 3. 

Do you know if this is a common problem, or have suggestions on things to try aside from what's included in the readme?

Thanks.

**Comment by lbusett** [comment]
Hi, 

Thanks for your interest. Could you be a bit more specific concerning the kind of problems you have for installation? 

Lorenzo

**Comment by PatrickJohnston** [comment]
Hi,

I managed to install it successfully. I don't know why I hadn't been able to for several weeks, but I'm glad it is fixed!

Thanks.
Patrick

**Comment by lbusett** [comment]
:+1: Thanks for reporting.
